import turtle

turtle.shape('turtle')
turtle.speed(10)

def smile():
    turtle.left(90)
    turtle.fillcolor('yellow')
    turtle.begin_fill()
    turtle.circle(100)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(-125, 50)
    turtle.pendown()
    turtle.fillcolor('blue')
    turtle.begin_fill()
    turtle.circle(15)
    turtle.penup()
    turtle.goto(-45, 50)
    turtle.pendown()
    turtle.circle(15)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(-95, 15)
    turtle.pendown()
    turtle.color('black')
    turtle.pensize(8)
    turtle.left(180)
    turtle.forward(45)
    turtle.penup()
    turtle.goto(-45, -40)
    turtle.color('red')
    turtle.pendown()
    turtle.circle(-48, 180, 10)

smile()
turtle.exitonclick()
